apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: helm-sentry
spec:
  package: ghcr.io/hops-ops/helm-sentry:{{ .Values.version }}
{{- if .Values.skipDependencyResolution }}
  skipDependencyResolution: true
{{- end }}
{{- if .Values.skipDependencyResolution }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: hops-ops-helm-sentryrender
spec:
  package: ghcr.io/hops-ops/helm-sentry-render:{{ .Values.version }}
{{- end }}
